### ISSUE TITLE
Support simplified syntax for new DLQ with queue properties

### ISSUE THREAD

**Issue by gmetzker** [gmetzker/serverless-plugin-lambda-dead-letter#12]
A plugin user may want to create new DLQs but also set queue properties.  Update `targetQueue` to  support queue properties.

Example Syntax:

```YAML
    deadLetter:
      sqs: 
        queueName: my-new-dlq  #New Queue Name
        delaySeconds:  # Integer
        messageRetentionPeriod:  # Integer
        receiveMessageWaitTimeSeconds:  # Integer
        visibilityTimeout:  # Integer
```

If possible support all [CF queue properties](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sqs-queues.html)
