### ISSUE TITLE
Support simplified syntax for new DL Topic with topic properties

### ISSUE THREAD

**Issue by gmetzker** [gmetzker/serverless-plugin-lambda-dead-letter#13]
A plugin user may want to create new DLTs but also set Topic properties.  Update `targetTopic` to  support topic properties.

Example Syntax:

```YAML
    deadLetter:
      sns: 
        topicName:  my-new-dlt   # New SNS Topic name
        displayName:    # Topic display Name
```

Topics don't appear to have many properties on the root object.  But maybe implement a direct pass through to CF when compiling the SNS Topic resource.
[See CF documentation](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-sns-topic.html)
