### ISSUE TITLE
Role associated with lamba doesn't have permission to SQS queue

### ISSUE THREAD

**Issue by Voochichichi** [gmetzker/serverless-plugin-lambda-dead-letter#20]
Using this plugin (Awesome, love it!) and I can't seem to get the role configuration to work properly.

So here's an extract from my serverless.yml

```
service: testProject

provider:
  name: aws
  runtime: dotnetcore1.0


plugins:
  - serverless-plugin-lambda-dead-letter

functions:
  Handler-TestHandler:
    handler: CsharpHandlers::Test.testProject.Handler::TestHandler
    deadLetter:
      targetArn:
        GetResourceArn: TestDlq
    events:
      - stream: arn:aws:kinesis:ap-southeast-2:*:stream/TestStream

resources:
  Resources:
    TestStream:
      Type: AWS::Kinesis::Stream
      Properties:
        Name: TestStream
        ShardCount: 1
    TestDlq:
        Type: AWS::SQS::Queue
        Properties:
          QueueName: TestDlq
    TestDlqPolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
          Queues:
            - Ref: TestDlq
          PolicyDocument: {
            "Version":"2012-10-17",
            "Statement":[
              {
                "Effect":"Allow",
 	              "Principal": "*",
                "Action":["SQS:*"],
                "Resource":"*"
              }
            ]}
````

The SQS is getting created with these permissions (I've really opened it up just to get it to work, then i'll scale it back correctly once i accomplish that)
![image](https://cloud.githubusercontent.com/assets/14302692/22052464/88a3a740-dd9e-11e6-987d-553e2bed4cd8.png)
(Im not even sure if I need to give the above policy document, I would have thought permission would come from the functions ROLE, much like how the Kinesis stream permissions work, through the role)

The SQS is being associated correctly to the lambda function:
![image](https://cloud.githubusercontent.com/assets/14302692/22052531/d6e26d60-dd9e-11e6-9695-b804b595b288.png)
However as you can see I have a warning that the Role does not have permissions to that SQS queue

I've got a role being created with the following inline policy which can correctly access the Kinesis stream I have asked it subscribe to, and to CloudWatch in general...

```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "logs:CreateLogGroup",
                "logs:CreateLogStream"
            ],
            "Resource": "arn:aws:logs:ap-southeast-2:*:*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "logs:PutLogEvents"
            ],
            "Resource": "arn:aws:logs:ap-southeast-2:*:*",
            "Effect": "Allow"
        },
        {
            "Action": [
                "kinesis:GetRecords",
                "kinesis:GetShardIterator",
                "kinesis:DescribeStream",
                "kinesis:ListStreams"
            ],
            "Resource": [
                "arn:aws:kinesis:ap-southeast-2:*:stream/TestStream",
            ],
            "Effect": "Allow"
        }
    ]
}
```
I would have assumed that the above general policy would also specific access to the SQS DLQ, but it does not?

**Comment by gmetzker** [comment]
I had a few iterations trying to figure out the policy as well.  With the proposal from #10 there might be a more simplified syntax that would compile the queue resource and policy document for you.

Until then here is the syntax I used in the custom resources...

I can't say which one of these is causing your issue but I noticed a few differences:

- You seem to missing the ID in the policy document.
- The `Statement` in the policy document might need an `SID` as well.
- For `Principal` I used `AWS: "*"`
- For `Resource` I directly referenced the queue.
- I added a condition on the arn so the policy only applies when it matches the Lambda Function arn.
  - To reference the lambda functions in the `Fn::GetAtt` you have to infer what serverless is going to use as the Lambda logical id. In CF.  In my case `serverlessLambda` ==> `ServerlessLambdaLambaFunction`


Let me know if this works for you.

```YAML
functions:
  serverlessLambda:
    name: my-serverless-lambda
    description: Lambda to test the serverless utility
    
    deadLetter:

      # Use the ARN of a resource defined in the resources section.
      targetArn:
        GetResourceArn: ServerlessTplLambdaDlQueue


resources:
    Resources:
      ServerlessTplLambdaDlQueue:
        Type: AWS::SQS::Queue
        Properties:
          QueueName: my-serverless-lambda-retry-queue

      ServerlessTplLambdaDlQueuePolicy:
        Type: AWS::SQS::QueuePolicy
        Properties:
          Queues:
            - Ref: ServerlessTplLambdaDlQueue
          PolicyDocument:

            # This probably needs something more unique 
            # like 'Fn::GetAtt: [ServerlessTplLambdaDlQueue, Arn]'  + '/SQSPolicy'
            Id: ServerlessTplLambdaDlQueueId  

            Version: '2012-10-17' 
            Statement:
              - Sid: Allow-Lambda-SendMessage
                Effect: Allow
                Principal:
                   AWS: "*"
                Action:
                  - SQS:SendMessage
                Resource:
                  Ref: ServerlessTplLambdaDlQueue
                Condition:
                  ArnEquals:
                    aws:SourceArn:
                      Fn::GetAtt: [ServerlessLambdaLambdaFunction, Arn]
```
