### ISSUE TITLE
Short hand syntax should support FIFO queues

### ISSUE THREAD

**Issue by gmetzker** [gmetzker/serverless-plugin-lambda-dead-letter#25]
SQS recently added support for 'fifo' queues.
If Cloudformation supports this  perhaps the plugin can support it to.  Use a regex match `.fifo$` to see if the queue name ends with `.fifo`.

If the queue name ends with `.fifo` then create a fifo queue  by:
* Set attribute:  `FifoQueue: true` ?
* Consider setting `ContentBasedDeduplication: true` or what ever the default queue attributes on when you create a fifo queue on the AWS web ui console.

- [x] Determine the default fifo queue attributes

- [x] Determine if Cloudformation supports this what what the syntax looks like

- [ ] During compilation time determine if the queue name matches the fifo format

- [ ] Create the queue with the default fifo attributes if it should be a fifo queue.

### Potential syntax
```YAML
  # 'functions' in serverless.yml

functions:
  createUser: # Function name
    handler: handler.createUser # Reference to function 'createUser' in code

    deadLetter:
      sqs:  createUser-dl-queue.fifo
```
