### ISSUE TITLE
Unexpected key 'DeadLetterConfig' found in params

### ISSUE THREAD

**Issue by TheSneak** [gmetzker/serverless-plugin-lambda-dead-letter#30]
I get the following error when I try to deploy my serverless service:
`Unexpected key 'DeadLetterConfig' found in params`
I have an existing SQS queue that I am trying to configure as the dead letter queue for my lambda function. Here is the relevant section of my serverless.yml:

```
plugins:
  - serverless-plugin-lambda-dead-letter

functions:
  testfunc:
    handler: index.handler
    deadLetter:
      targetArn: arn:aws:sqs:us-east-1:000000000000:us-east-1-DeadLetterQueueSQS-XXXXXXXXXXXXX
```
