### ISSUE TITLE
Support intrinsic functions

### ISSUE THREAD

**Issue by nitely** [gmetzker/serverless-plugin-lambda-dead-letter#32]
Hey. First of, awesome project. Thanks!

Support for intrinsic functions (Get, Import, etc) would be awesome. Something like this:

```yml
deadLetter:
  targetArn:
    Fn::ImportValue: ${self:custom.imports.another-stack.dlq}
```
