### ISSUE TITLE
Feature Request: CloudWatch Alarm Configuration for Messages in DLQ

### ISSUE THREAD

**Issue by flyinbutrs** [gmetzker/serverless-plugin-lambda-dead-letter#33]
When using an SQS queue as the target, it would be very convenient to be able to supply the bare minimum details (threshold, OK action, Alarm action) and have it setup a CW Alarm for the DLQ to alert when there are messages that were rejected.

something like this:
````
    deadLetter:
      sqs:
        queueName: ${opt:stage}-function-dlq
        messageRetentionPeriod: 200000
        alarm:
          threshold: 0
          OkAction: sns_arn
          AlarmAction: sns_arn
````
