### ISSUE TITLE
Can't work with documented syntax

### ISSUE THREAD

**Issue by kalinchernev** [gmetzker/serverless-plugin-lambda-dead-letter#37]
Relates to #32

In service A, I got the resource created successfully on deployment:

```yaml
resources:
  Resources:
    LambdaFailureQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:provider.stage}-${self:service}
        MessageRetentionPeriod: '1209600'
        VisibilityTimeout: '60'
```

and a handler in the same `serverless.yml` file successfully gets triggered by

```
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - LambdaFailureQueue
              - Arn
```

So far, so good. Then, in service B, I'm trying to attach fallback behavior to this previously created dead letter queue.

These don't work:

```yaml
    deadLetter:
      targetArn:
        - 'Fn::Join':
          - ':'
          -
            - 'arn:aws:sqs'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - '${self:provider.stage}-ingestion-dead-letter-queue'
```

Results in:

```
Function property parseCsv.deadLetter.targetArn object is missing GetResourceArn property.
```

```yaml
    deadLetter:
      targetArn:
        GetResourceArn:
          - 'Fn::Join':
            - ':'
            -
              - 'arn:aws:sqs'
              - Ref: 'AWS::Region'
              - Ref: 'AWS::AccountId'
              - '${self:provider.stage}-ingestion-dead-letter-queue'
```

Results in 
```
Expected params.LogicalResourceId to be a string
```

The only syntax, which works is the following:

```yaml
    deadLetter:
      targetArn: 'arn:aws:sqs:${self:provider.region}:12345:${self:provider.stage}-ingestion-dead-letter-queue'
```

I've tried using [serverless-pseudo-parameters](https://www.npmjs.com/package/serverless-pseudo-parameters) in order to have the following syntax:

```yaml
    deadLetter:
      targetArn: 'arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:${self:provider.stage}-ingestion-dead-letter-queue'
```

However, this results in 

```
Function property parseCsv.deadLetter.targetArn object is missing GetResourceArn property.
```

Another approach I tried:

Make an export from service A:

```yaml
  Outputs:
    LambdaFailureQueue:
      Description: The dead letter queue for AWS Lambda handlers.
      Value:
        Fn::GetAtt: ["LambdaFailureQueue", "Arn"]
      Export:
        Name: "${self:custom.eubfrEnvironment}:${self:service}:LambdaFailureQueue"
```

And then try an import in service B:

```yaml
    deadLetter:
      targetArn:
        Fn::ImportValue: ${self:custom.eubfrEnvironment}:ingestion-dead-letter-queue:LambdaFailureQueue
```

-> not working

```
Function property parseCsv.deadLetter.targetArn object is missing GetResourceArn property.
```

trying also 

```yaml
    deadLetter:
      targetArn:
        GetResourceArn:
          Fn::ImportValue: ${self:custom.eubfrEnvironment}:ingestion-dead-letter-queue:LambdaFailureQueue
```

-> again error

```
Expected params.LogicalResourceId to be a string
```

My goal is to find a way to get rid of the specific account number, as a wildcard also results in:

```
Function property parseCsv.deadLetter.targetArn = 'arn:aws:sqs:eu-central-1:*:chernka204-ingestion-dead-letter-queue'.  This is not a valid sns or sqs arn. 
```
