### ISSUE TITLE
lambda can't send message to dlq

### ISSUE THREAD

**Issue by nivpenso** [gmetzker/serverless-plugin-lambda-dead-letter#40]
Hi,

I found it not possible to send messages to the DLQ since the execution role of the lambda doesn't include SendMessage policy for the dead letter queue.

It is important to mention that it doesn't matter whether the SQS contains a policy that allows it to receive messages from the Lambda's ARN.

I also contacted Amazon support and they verified that this behavior is right.

**Comment by jhdrn** [comment]
Hopefully you figured it out, but as I also ran into the same problem I'm sharing my solution:

Add a role statement to serverless.yml:

```
provider:
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - sqs:SendMessage
      Resource:
        - ARN for SQS queue goes here
```

Ideally this would be done automatically by the plugin.
