### ISSUE TITLE
Serverless configuration validation warning

### ISSUE THREAD

**Issue by greenlynx** [gmetzker/serverless-plugin-lambda-dead-letter#42]
Serverless is throwing a warning when it validates its configuration before deployment:

```
Serverless: Configuration warning at 'functions.foo': unrecognized property 'deadLetter'
```

Excerpt from `serverless.yml`:

```yml
functions:
  foo:
    handler: src/handlers/events/foo.bar
    deadLetter:
      targetArn:
        GetResourceArn: DeadLetterQueue
```

According to the documentation for [Service configuration validation](https://www.serverless.com/framework/docs/configuration-validation/):

>If you received a configuration warning it could mean that:
> - Configuration related to external plugin does not have an associated JSON Schema. In such cases, please report the issue with the plugin author and provide them the details on how to extend validation schema in order to permanently correct the issue.

The same documentation page says that this warning is likely to become an error in future, which would break this plugin.
