### ISSUE TITLE
Local DLQ is not created in serverless-offline

### ISSUE THREAD

**Issue by shashiranjan84** [gmetzker/serverless-plugin-lambda-dead-letter#43]
I am trying to use the DLQ plugin `serverless-plugin-lambda-dead-letter` as explained in the blog https://www.serverless.com/plugins/serverless-plugin-lambda-dead-letter, but when I test things locally using serverless-offline, DLQ is not created 

Here is my config:

```
service: integration-delighted-lambda

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-plugin-lambda-dead-letter
  - serverless-offline-sqs
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  timeout: 10
  memorySize: 128
  role: <role>
  tracing:
    lambda: true

custom:
  webpack:
    includeModules: false
    packager: yarn
  serverless-offline-sqs:
    autoCreate: true
    apiVersion: '2012-11-05'
    endpoint: http://0.0.0.0:9324
    region: eu-west-1
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

functions:
  fooTestHandler:
    name: test-serverless
    handler: src/testHandler.testHandler
    maximumRetryAttempts: 1
    layers:
      - { Ref: NodeModulesLambdaLayer }
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - MyQueue
              - Arn
    deadLetter:
      sqs: delighted-sqs-dl-queue
      delaySeconds: 60
      maximumMessageSize: 4096
      messageRetentionPeriod: 200000
      receiveMessageWaitTimeSeconds: 15
      visibilityTimeout: 300

layers:
  nodeModules:
    path: ../../serverless-build

resources:
  Resources:
    MyQueue:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: 'my-sqs-queue'

```

I only see `my-sqs-queue` being created in local ElasticMQ.
