### ISSUE TITLE
Configuration error at 'functions[function-name]' unrecognized property 'deadLetter'

### ISSUE THREAD

**Issue by jordanmaxfightcamp** [gmetzker/serverless-plugin-lambda-dead-letter#46]
Receiving this error after trying to use this plugin:

```
 Serverless Error ----------------------------------------
 
  Configuration error at 'functions['sessions-stream-listener']': unrecognized property 'deadLetter'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.17.0
     Framework Version:         2.46.0 (local)
     Plugin Version:            5.3.0
     SDK Version:               4.2.3
     Components Version:        3.12.0
```

here is my code:

```
plugins:
  - serverless-plugin-lambda-dead-letter

functions:
  foo:
    handler: handler.foo

    deadLetter:
      sqs: ${self:custom.foo}
    events:
      - stream:
          type: dynamodb
          arn: ${self:custom.foo}}
```

Any suggestions? not sure what im doing wrong.
